### ISSUE TITLE
\MossApp\MossApp\Publish,i cant find the installer in this path

### ISSUE THREAD

**Issue by xychencs** [shanemay/MossApp#2]
\MossApp\MossApp\Publish,i cant find the installer in this path, the path is not available

**Comment by nottalada** [comment]
@xychencs I'm guessing that this is a C# application that you'd need to compile yourself in Visual Studio.

**Comment by shanemay** [comment]
I have updated the project to include the publish folder. By default, my ignore file include the publish folder. That has been fixed.
