### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by zifa25796** [shanemay/MossApp#5]
After trying to send request, the entire program just stop running. The window shows Not Responding.
Only testing it with two files.

**Comment by jstarr35** [comment]
It can take some time for the results to return, and the interface will be unresponsive until that time. But I have found that if it is taking an excessive amount of time, it is likely due to a misconfigured request. What were the parameters you used for your request?

**Comment by zifa25796** [comment]
All the config is just default ones, other than the userID, and the source file location.
I haven't waited for a long time, perhaps i should just give it a while.
![image](https://user-images.githubusercontent.com/59847842/134428675-bf2fe9ba-c61b-4faf-a79d-eaa1466a4310.png)

**Comment by jstarr35** [comment]
I can't reach the server right now, so I would wait a while and then try again. Occasionally the server is overloaded with requests.

**Comment by zifa25796** [comment]
Ah ye, the server is back on. Thank you very much.
