### ISSUE TITLE
Not detecting similar code

### ISSUE THREAD

**Issue by Ayush-Goyal-coding** [shanemay/MossApp#7]
I am not sure if this is the issue with Moss or MossApp or if I am doing something wrong, But:
I created two files s1.cpp & s2.cpp and both have same code:
```
#include <iostream>
using namespace std;
int main(){
cout << "testing";
return 0;
}
```
I expected mossApp to tell me that these two files exactly match, but I am not getting the desired results.
I tried different values of `m `and `n` as well, but I don't get the desired results.

Here is the screenshots for more reference. 

SS while sending the request
![image](https://user-images.githubusercontent.com/25609044/215863536-5c831038-9225-4ea8-bdb3-08ce34c8e9c8.png)

SS of result:
![image](https://user-images.githubusercontent.com/25609044/215864049-37c6c212-56d0-4304-8c09-0d33877ef9ae.png)

Please let me know if you want more information. I am currently using Windows 11.

**Comment by jstarr35** [comment]
You need to uncheck the **Use Directory Mode** checkbox. 

> The -d option specifies that submissions are by directory, not by file. That is, files in a directory are taken to be part of the same program, and reported matches are organized accordingly by directory.
